name: Close PR Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  Close:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: prview/prview.github.io

      - name: Remove Preview folder
        run: rm -r ${{ github.event.pull_request.number }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: prview/prview.github.io
          personal_token: ${{ secrets.PR_PAT }}
          publish_dir: ./
          user_email: 104292447+prview@users.noreply.github.com
          user_name: prview
